### ISSUE TITLE
This project seems misleading

### ISSUE THREAD

**Issue by SoftwareDreamer** [dineshsonachalam/redis-cloudflare-kv#1]
Hi..

while I like the ambition here, I think this is a non-sensical comparison. The reason is you are accessing KV in a very inefficient way, by using the HTTP API, which talks to a **global** REST endpoint in america. It is actually discouraged to access KV this way, instead you should access it via a worker script, which means KV is read from and written to in the closest Cloudflare PoP. This is mentioned in the community discord (somewhere) by CF staff and also on discourse forums, e.g. here: https://community.cloudflare.com/t/workers-kv-very-slow-accessing-data-thought-api/266932/2

**Comment by dineshsonachalam** [comment]
Thanks @HKochniss for the detailed comment. I will validate accessing KV with the worker and their latency. Then will update this project.
